version: 2
jobs:
  test:
    docker:
      - image: ymtszw/elm_for_ci@0.19
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - elm-stuff-{{ .Branch }}-{{ .Revision }}
          - elm-stuff-{{ .Branch }}-
          - elm-stuff-
      - run: elm-test
      - save_cache:
          paths:
            - elm-stuff
            - tests/elm-stuff
          key: elm-stuff-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  build:
    jobs:
      - test
